### ISSUE TITLE
"argument out of range" error in eta method

### ISSUE THREAD

**Issue by sternschnuppe** [ifreecarve/nmea_plus#2]
## If ETA is not set (i.e. "0-0 24:60" or "0-0 00:00") the method stops throwing "argument out of range (ArgumentError)".

- Error message:

/home/user/.rvm/gems/ruby-2.3.0/gems/nmea_plus-1.0.12/lib/nmea_plus/message/ais/vdm_payload/vdm_msg5.rb:26:in `initialize': argument out of range (ArgumentError)

from /home/user/.rvm/gems/ruby-2.3.0/gems/nmea_plus-1.0.12/lib/nmea_plus/message/ais/vdm_payload/vdm_msg5.rb:26:in `new'

from /home/user/.rvm/gems/ruby-2.3.0/gems/nmea_plus-1.0.12/lib/nmea_plus/message/ais/vdm_payload/vdm_msg5.rb:26:in `eta'

from Decode_NMEA.rb:72:in `block in main'

from /home/user/.rvm/gems/ruby-2.3.0/gems/nmea_plus-1.0.12/lib/nmea_plus.rb:103:in `block in each_complete_message'

from /home/user/.rvm/gems/ruby-2.3.0/gems/nmea_plus-1.0.12/lib/nmea_plus.rb:56:in `block in each_message'

from /home/user/.rvm/gems/ruby-2.3.0/gems/nmea_plus-1.0.12/lib/nmea_plus.rb:46:in `each_line'

from /home/user/.rvm/gems/ruby-2.3.0/gems/nmea_plus-1.0.12/lib/nmea_plus.rb:46:in `each_message'

from /home/user/.rvm/gems/ruby-2.3.0/gems/nmea_plus-1.0.12/lib/nmea_plus.rb:81:in `each_complete_message'

from Decode_NMEA.rb:17:in `main'

- Example sentences
```
!AIVDM,2,1,6,B,53JNnF42BiCWTP7?3KE<B18uHE:222222222220l1h>5540Ht<P000000000,0*6A
!AIVDM,2,2,6,B,00000000000,2*21
!AIVDM,2,1,0,A,539egL400000@?KOOF0u8<62000000000000000l10C33t0Ht0R0C@UDQp00,0*50
!AIVDM,2,2,0,A,00000000000,2*24
!AIVDM,2,1,3,B,539J@cT00000@7GCC<0P4T00000000000000000l0h<22t0Ht0P000000000,0*3B
!AIVDM,2,2,3,B,00000000000,2*24
!AIVDM,2,1,3,B,539QeeT00000@;?S7818DE0E884Pp0000000000t2p64440Ht00000000000,0*66
!AIVDM,2,2,3,B,00000000000,2*24
!AIVDM,2,1,6,A,539`vQ400000@SGKGP0P4q<D5@000000000000150@@23t0Ht0B0C@UDQh00,0*6B
!AIVDM,2,2,6,A,00000000000,2*22
!AIVDM,2,1,8,A,539I@g400000@;W3;B0@EA@lE:1@4pf3G5v0001I9P963t000011@TUL<><<,0*0B
!AIVDM,2,2,8,A,13hjn<<<==@,2*0E
```
- Workaround:
`begin eta = message.ais.eta; rescue eta = nil; end`

**Comment by ifreecarve** [comment]
> unfortunately grave accents are interpreted so I can't use any of these sentences

I'm not sure what you mean.  Can you paste those sentences here in a [fenced code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks)?

**Comment by ifreecarve** [comment]
In these examples, it looks like the ETA is meant to be nil: zeros for the day and month, 24 for hour and 60 for the seconds.

**Comment by sternschnuppe** [comment]
For the sake of completeness I added a sentence with a backtick.

**Comment by ifreecarve** [comment]
Thanks, I used your data in rspec tests
